#!/bin/bash


dev(){

  # lein repl :start :host 0.0.0.0 :port 7788
  # lein repl :headless :host 0.0.0.0 :port 7788
  # lein repl :connect 0.0.0.0:7878
  lein repl :headless

}

run_dev(){
  lein run dev
}

run_uberjar(){
  java -jar target/app.standalone.jar
}

uberjar(){
  lein with-profiles +prod uberjar
  # java -jar target/app.uber.jar 
}

dock() {
    NS="lab.cloud"
    NAME="${NS}.app-http-layer-1"
    NETWORK="lab.cloud"
    DOCKERFILE_PATH=../../docker/ubuntu18-openjdk11-lein/Dockerfile

    docker build -t ${NAME} -f ${DOCKERFILE_PATH} ./
    docker network create ${NETWORK} || true
    docker run  --rm \
                --cpus=4.0 \
                --memory=1g \
                --name ${NAME} \
                -it \
                --network ${NETWORK} \
                --expose 7788 \
                --expose 8080 \
                -p 7788:7788 \
                -p 8080:8080 \
                -v "$(pwd)":/ctx/app \
                -v "$(pwd)"/.user:/root \
                -v "$(cd ../ && pwd)"/core:/ctx/core \
                 ${NAME} \
                 bash -c "cd /ctx/app; bash;"
}

dock1(){

    NS="lab.cloud"
    NAME="${NS}.app-http-layer-1-prod1"
    NETWORK="lab.cloud"
    DOCKERFILE_PATH=../../docker/alpine-openjdk11-min/Dockerfile

    docker build -t ${NAME} -f ${DOCKERFILE_PATH} ./
    docker network create ${NETWORK} || true
    docker run  --rm \
                --cpus=4.0 \
                --memory=1g \
                --name ${NAME} \
                --network ${NETWORK} \
                --expose 8080 \
                -p 8080:8080 \
                -v "$(pwd)":/ctx/app \
                 ${NAME} 

}

dock2(){

echo ""

}

"$@"