#!/bin/bash


dev(){

  # lein repl :start :host 0.0.0.0 :port 7788
  # lein repl :headless :host 0.0.0.0 :port 7788
  # lein repl :connect 0.0.0.0:7878
  lein repl :headless

}

run_dev(){
  lein run dev
}

run_uberjar(){
  java -jar target/app.standalone.jar
}

uberjar(){
  lein with-profiles +prod uberjar
  # java -jar target/app.uber.jar 
}

native(){
  lein native-image
}

run_java_sh(){
  # JAVA_MAX_MEM_RATIO=100
  export JAVA_APP_JAR=target/app.standalone.jar
  bash run-java.sh "$@"
}


dc(){
  docker-compose --compatibility \
  -f dc.yml \
  "$@"
}

up(){
  dc up -d --build "$@"
}

down(){
  dc down "$@"
}

run(){
  # https://docs.docker.com/compose/reference/run/
  $1 run --service-ports $2 bash -c "bash;"
}

term(){
  $1 exec $2 bash -c "bash;"
}



"$@"